import os

BOT_TOKEN = os.environ.get("BOT_TOKEN", "")
OWNER_ID = int(os.environ.get("OWNER_ID", "0"))

TOP_SYMBOLS = [
    "BTC/USDT", "ETH/USDT", "BNB/USDT", "SOL/USDT", "XRP/USDT",
    "TON/USDT", "DOGE/USDT", "ADA/USDT", "AVAX/USDT", "DOT/USDT",
    "MATIC/USDT", "LINK/USDT", "UNI/USDT", "ATOM/USDT", "LTC/USDT",
    "BCH/USDT", "APT/USDT", "OP/USDT", "ARB/USDT", "SUI/USDT"
]

RSI_OVERSOLD = 30
RSI_OVERBOUGHT = 70

SIGNAL_INTERVAL_MINUTES = 15
